[package]
name = "otlp-embedded"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.6"
futures = "0.3"
hex = "0.4"
itertools = "0.12"
mime_guess = "2"
opentelemetry-proto = { path = "/Users/bugenzhao/Developer/opentelemetry-rust/opentelemetry-proto", features = ["gen-tonic", "trace", "with-serde"] }
prost = "0.12"
rust-embed = { version = "8", features = ["mime-guess"] }
schnellru = "0.2"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tonic = { package = "madsim-tonic", version = "0.4.1" }
tracing = "0.1"
