[package]
name = "otlp-tempo-dump"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
itertools = "0.12"
opentelemetry-otlp = "0.14"
opentelemetry_sdk = { version = "0.21", default-features = false }
pbjson = "0.6"
prost = "0.12"
schnellru = "0.2"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tonic = "0.10"
tracing = "0.1"

[build-dependencies]
pbjson-build = "0.6"
tonic-build = "0.10"
