[package]
name = "otlp-tempo-dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
indextree = "4"
itertools = "0.11"
opentelemetry = { version = "0.20", features = [
    "rt-tokio",
], default-features = false }
opentelemetry-otlp = "0.13"
# opentelemetry-proto = { version = "0.3", features = ["gen-tonic", "traces"] }
pbjson = "0.5"
prost = "0.11"
schnellru = "0.2"
serde = "1"
serde_json = "1"
# opentelemetry_api = "0.20"
# need tokio runtime to run smoke tests.
# opentelemetry_sdk = { features = [
#   "trace",
#   "rt-tokio",
#   "testing",
# ], version = "0.20" }
# serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
# tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.9"
tracing = "0.1"

[build-dependencies]
pbjson-build = "0.5"
tonic-build = "0.9"
